dist: trusty
sudo: false

language: cpp

compiler:
  - gcc

addons:
  apt:
    packages:
    - qtbase5-dev

script:
  - qmake -qt=qt5 -Wall projectfiles/QtCreator/NFK-Lobby.pro
  - make -j$(nproc)

notifications:
  irc: "chat.freenode.net#nfk-lobby"
